### ISSUE TITLE
External Editor Solution

### ISSUE THREAD

**Issue by monoai** [walcht/neovim-unity#5]
Good evening! Thank you for the script, my old unitynvim script from somewhere else were too bare bones, yours seems to make nvr work properly again.
I came to provide a solution regarding the external editor problem, I've forgotten where I found it but you don't ***have to install VS Code*** in order to regenerate project files. Simply making a blank file named `code` (or `code.exe` used to work on old versions) will somehow make Unity *think* that you have VS Code and enable you to regenerate project files.
I've done this way for a few projects now, so I hope this helps out a lot on simplifying things and not needing to install another editor.
![image](https://github.com/walcht/neovim-unity/assets/46586720/1726c124-319e-4280-ba6e-91d4c5a6da17)

**Comment by walcht** [comment]
Hi,

Apologies for the late reply (busy week) and hank you for your interest for this immature project 😄  

That seems great! I think I will put a ```code``` file somewhere and test whether this works or not. What I think is definitely needed is the extension plugin for these editors (at least one, VSCode plugin seems to be installed by default).

What is way much better, I believe, is some way to bypass this whole GUI step (it's driving me crazy to have to do this for every new file!).
This article (pointed by mjtorn (Ty!) in another issue) seems to provide another method to do that:
https://spaceandtim.es/code/nvim_unity_setup/

We can probably figure out what that "Regenerate Project Files" calls under the hood. Thing is, I may not have the rights to call it directly (if it is some internal function protected by some God-knows-how-to-understand license)

Note: I may respond a bit late this period. But after the 14th of February I will give full attention to this project.

**Comment by walcht** [comment]
it worked fine after testing! (even after completely removing VSCode)
![image](https://github.com/walcht/neovim-unity/assets/89390465/40edb52d-0ebf-4f2b-86b9-89f15fcb8ba5)

Updated README and added ```code``` empty file to ```scripts``` folder.
Thanks!

**Comment by walcht** [comment]
I will close this issue for the moment.
I will also open an enhancement issue for potentially bypassing this whole GUI thing by using some CLI commands.
Thanks again and cheers!

**Comment by walcht** [comment]
Updated the guide to make use of this custom Neovim plugin [com.walcht.ide.neovim](https://github.com/walcht/com.walcht.ide.neovim) (adopted from official Visual Studio package) that elegently solves this.
